### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ChristophHaag** [GodotVR/godot_openxr#1]
For the most part this requires adding a code path for Windows around the OpenGL handling.

Spec: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_opengl_enable

In OXRCalls.c we need something like

```c
#ifdef _WIN32
#define XR_USE_PLATFORM_WIN32
#else
#define XR_USE_PLATFORM_XLIB
#endif
```

and a similar ifdef around the code using the `XrGraphicsBindingOpenGLXlibKHR` struct is required, using the `XrGraphicsBindingOpenGLWin32KHR` instead.

This requires getting these values

    hDC is a valid Windows HW device context handle.
    hGLRC is a valid Windows OpenGL rendering context handle.

On Linux the code uses the "current" X display, glx gontext and glx drawable (window)
```c
XOpenDisplay(NULL);
glXGetCurrentContext();
glXGetCurrentDrawable();
```
but ideally we get the gl context and window handles that godot uses from godot itself.

**Comment by BastiaanOlij** [comment]
Half of this is in there  now :)

**Comment by BastiaanOlij** [comment]
I'm going to close this now that we have basic support merged in. Still a long road ahead but we've taken the first major step :)
