### ISSUE TITLE
Missing instructions in Getting Started

### ISSUE THREAD

**Issue by dominiks** [GodotVR/godot_openxr#111]
Hi, I followed the getting started instructions to the point where it says

> Now you can press the run button to start your project and you should be able to look around.

But the scene started in normal mode. I added a script to the root of the scene to call `$FPSController.initialise()` in `_ready` and that fixed it. Would probably be very helpful to others if it was added to the guide.

**Comment by kuhnchris** [comment]
THANK YOU. I was just having this issue aswell. I assumed I may have to look up the godot-openvr repo aswell, but, initializing the FPSController worked. Cheers!

**Comment by BastiaanOlij** [comment]
I'm working on a PR to make that automatic: https://github.com/GodotVR/godot_openxr/pull/131
Though the debate is still open whether to just run it always. It was made optional because we often combined the plugin with others depending on whether you were running on desktop or mobile.

**Comment by m4gr3d** [comment]
Closing as this issue was resolved in the latest releases of the plugin.
