### ISSUE TITLE
No way currently to get bounds of room in roomscale VR.

### ISSUE THREAD

**Issue by dmitsuki** [GodotVR/godot_openxr#115]
There is currently no method to get the points relative to origin that define the size of the play area.

**Comment by BastiaanOlij** [comment]
That is the way we do this in the OpenVR plugin. 

For OpenXR in Godot 3 we should add a method to obtain the bounds to the OpenXRConfig object and implement a similar method that we mark the bounds as dirty if changed, than retrieve new data if required on requesting the bounds. We should also store these without reference frame and scaling applied so we can reuse the data when requested as a result of changing either. 

Note that in Godot 4 we've added a template API that needs to be implemented by the plugin:
https://github.com/godotengine/godot/pull/49942

**Comment by BastiaanOlij** [comment]
This is resolved through https://github.com/GodotVR/godot_openxr/pull/133
