### ISSUE TITLE
Hello! Into which Godot folder should I clone this repo to make it build? 

### ISSUE THREAD

**Issue by Fredrum** [GodotVR/godot_openxr#130]
Hi!
I'm trying to get this building on Ubuntu20 but I can't figure out where I need to git clone this to?
Does anyone know?

Cheers!

**Comment by BastiaanOlij** [comment]
@Fredrum if you want to compile the plugin you would normally do this outside of your Godot project, just clone it in its own folder, follow the build instructions in the readme, and then copy the resulting `addons/godot-openxr` folder into your godot project.

**Comment by BastiaanOlij** [comment]
When using OpenXR you need to use Monado as an OpenXR runtime.

While we don't work on it anymore we also have OpenHMD as a driver that does it more direct with Godot however Monado uses OpenHMD as well and offers a lot more stuff to make the experience better. Can highly recommend using their technology if you don't want to go the SteamVR route.
