### ISSUE TITLE
Missing ButtonEvent for trigger touching (button 16)

### ISSUE THREAD

**Issue by balintbarna** [GodotVR/godot_openxr#135]
A very strange bug: I have a debug display which displays the state of all buttons. It shows a state change for button 16 when I touch the trigger with my index finger, but the `button_pressed` event isn't firing. All other buttons/touches and corresponding events seem to work so far, except for this mysterious number 16.

Windows, Godot 3.4 stable, OpenXR installed from assetlib, Oculus Quest PCVR over AirLink

**Comment by balintmaci** [comment]
Also there seems to be no button value for the little thumb rest touch area of the controller (e.g. to the right of XY)

**Comment by balintmaci** [comment]
@BastiaanOlij any ideas?

**Comment by BastiaanOlij** [comment]
Sorry missed this issue, too many notifications on github, gets lost easily.

No idea off the top of my head, sounds like an issue on the Godot side, will have to investigate to see where it traps this, might just be checking the first 16 buttons only as that was once a limit in Godot.

**Comment by balintmaci** [comment]
@BastiaanOlij 
I cannot confirm that as none of the other VR button IDs are higher than 15, but just looking at GlobalScope there's constants that are higher so it'd be weird if it was an engine bug, it's definitely a possibility though.

**Comment by balintbarna** [comment]
Closing as not using it anymore.
