### ISSUE TITLE
Right eye flickers when `Viewport#transparent_bg` is enabled after `XR_SESSION_STATE_READY` state

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_openxr#139]
#### Repro steps:

- In [first_person_controller_vr.gd](https://github.com/GodotVR/godot_openxr/blob/master/demo/addons/godot-openxr/scenes/first_person_controller_vr.gd), add `_get_xr_viewport().transparent_bg = true` either to [`_on_openxr_session_begun`](https://github.com/GodotVR/godot_openxr/blob/780fbbbc27d2a2a9560ad5fd3415338ac1885b03/demo/addons/godot-openxr/scenes/first_person_controller_vr.gd#L92), [`_on_openxr_visible_state`](https://github.com/GodotVR/godot_openxr/blob/780fbbbc27d2a2a9560ad5fd3415338ac1885b03/demo/addons/godot-openxr/scenes/first_person_controller_vr.gd#L104) or [`_on_openxr_focused_state`](https://github.com/GodotVR/godot_openxr/blob/780fbbbc27d2a2a9560ad5fd3415338ac1885b03/demo/addons/godot-openxr/scenes/first_person_controller_vr.gd#L100).
- When the demo is run on a Quest device, the right eye flickers continuously.
- This doesn't happen if `transparent_bg` is set in [`initialise`]().

**Comment by m4gr3d** [comment]
@BastiaanOlij I have only been able to test on the Quest but this could also be an issue on other platforms.

**Comment by BastiaanOlij** [comment]
Strange, this is caused by Godot forgetting that we're using external textures and recreating the buffers on the Godot side. It's the same issue we had when you resized the preview window on desktop. That was fixed but possibly I only applied the fix for resizing, not when changing transparency. I'm assuming this was tested on the latest 3.x ?

**Comment by ChristophHaag** [comment]
Also an issue for #101

**Comment by BastiaanOlij** [comment]
Found the issue, I think something changed in the cleanup code of textures at some point. As we create a wrapper Texture object around our OpenGL texture supplied by the plugin, on changing the transparency setting this texture object is destroyed (as we recreate a new render target with proper settings for transparency) and our current right eye texture along side it. Hence the flicker as one texture in the texture chain is now missing.

This fixes it: https://github.com/godotengine/godot/pull/56148

**Comment by BastiaanOlij** [comment]
@m4gr3d let me know if the fix I did fixes this for you as well, if so we can close this:)

**Comment by m4gr3d** [comment]
@BastiaanOlij Yep, that fixed the issue!
