### ISSUE TITLE
Fine-grained Rumble Control?

### ISSUE THREAD

**Issue by tom95** [GodotVR/godot_openxr#144]
Hi! In https://github.com/GodotVR/godot_openxr/blob/780fbbbc27d2a2a9560ad5fd3415338ac1885b03/src/openxr/OpenXRApi.cpp#L2708 you noted that there will be a dedicated interface for better controlling haptic output. I was wondering whether there is already some design ideas on how this will be achieved. Will it become part of the core Godot ARVR interface, be added to one of the existing GDNative classes, or as a new class?

If this has already been discussed, please go ahead and close the issue. I didn't find any mention in this repo :)

**Comment by BastiaanOlij** [comment]
I was planning to add an OpenXRHaptic node similar to what I've done with OpenVR, but seeing there is no proper interface to edit the actions, and we're keeping the action bindings hardcoded for Godot 3 I'm not sure it's worth the effort.

For Godot 4 I'm working on a full action map editor though I've been sidetracked this month porting the plugin to core (also sort of on a xmas break right now even though I'm still doing a few things), so yeah for Godot 4 we should have all haptics working similar to what is in the OpenXR spec.

**Comment by tom95** [comment]
Hey, thanks for the explanation. Sounds like a good solution to me, looking very much forward to the new interface in godot 4 then! Hope you'll still have a good holiday :)
