### ISSUE TITLE
No hand models after loading first_person_controller_vr.tscn

### ISSUE THREAD

**Issue by Looki2000** [GodotVR/godot_openxr#150]
I followed wiki, but there are errors on console:
`ERROR: Cannot open file 'res://.import/left_hand.glb-77ac71087f4863f9f653fbf9e0d7f139.scn'.
   at: (core/io/resource_format_binary.cpp:984)
ERROR: Cannot open file 'res://.import/right_hand.glb-3c383114f6b2b559f4827c32305c15a4.scn'.
   at: (core/io/resource_format_binary.cpp:984)`

When I use "Instance Child Scene" to load first_person_controller_vr.tscn there are no hands. Only ARVR controllers.
I use Godot 3.4 and plugin version 1.1.0
![image](https://user-images.githubusercontent.com/89589699/147890779-5275c80c-1667-453d-9828-863106936ded.png)

**Comment by dominiks** [comment]
You have to add the `left_hand_mesh.tscn` and `right_hand_mesh.tscn` like this:

![grafik](https://user-images.githubusercontent.com/109005/147923314-1c629d80-26b2-4f2e-8dc0-aa4f481fe8bc.png)

The controller nodes have no visual representation by themselves.

**Comment by BastiaanOlij** [comment]
Indeed, the hand meshes are not added by default to the controller scene, not everyone wants to use them.

**Comment by m4gr3d** [comment]
Closing the issue as the question was answered. @Looki2000 Feel free to reopen if needed.
