### ISSUE TITLE
Where can i download version 1.1.1?

### ISSUE THREAD

**Issue by forecaster-cyber** [GodotVR/godot_openxr#151]
I want to use it with Godot 3.4.2 to make a passthrough game!

**Comment by BastiaanOlij** [comment]
We only released it officially yesterday, it can be found on the releases page here: https://github.com/GodotVR/godot_openxr/releases/tag/1.1.1
It can also be downloaded from the asset library from within Godot itself.

**Comment by m4gr3d** [comment]
Closing the issue as the question was answered. @forecaster-cyber Feel free to reopen if needed.
