### ISSUE TITLE
Performance comparison between VR and default

### ISSUE THREAD

**Issue by booger-bubble** [GodotVR/godot_openxr#154]
**Godot Version**
3.4.2 (GLES 3)

**Godot OpenXR Version**
1.1.1 from AssetLib (even though the displayed version is still 1.1.0), as well as 1.1.0

**System Information**
OS: Windows 10
HMD: HTC Vive Pro
CPU: AMD Ryzen 7 2700X
GPU: GeForce RTX 2060 (497.29)

Hi, first of all, thank you for your great work on integration XR with Godot.
I have compared framerates of VR and default FPS camera:

- VR: ≈ 42 fps
- Default: ≈ 200 fps (3840x2160)

Is this something expected, or am I missing something here?

**Comment by BastiaanOlij** [comment]
What is the project you're using to test with this? To me it feels like it's just not able to hit 90fps and SteamVR is throttling it down to 45fps and using reprojection to fill in the in between frames.

Keep in mind that the Vive Pro has a resolution of 1440x1600 per eye, so we could be rendering at 2880x3200 per eye. So say we do hit 90fps, that is comparable to 180fps at your native resolution.

Mind you, there could very well be something wrong, without a project to profile on and see where the performance is lost, it's a little hard to say.

**Comment by booger-bubble** [comment]
Hi, I did several performance tests and it seems that performance is comparable for default and XR.
