### ISSUE TITLE
Oculus Quest Grip axis out of range

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot_openxr#157]
The Oculus Quest controllers are reporting JOY_VR_ANALOG_GRIP positions in the range -1.0 to 1.0 rather than 0.0 to 1.0.

This can be demonstrated by using the Godot XR Tools hands, then in LeftHand.gd and RightHand.gd uncommenting the print statements. The following is printed **(note this is after multiplying the grip by 2.5)**:
```   
    Grip: -2.466667 Trigger: 0
    Grip: -2.48896 Trigger: 0
    ....
    Grip: 2.453722 Trigger: 0
    Grip: 2.471102 Trigger: 0
```

The out-of-range values cause the LeftHand.gd and RightHand.gd to feed negative values into the animation tree, which results in the animations freezing partially gripped after the user has released the grip buttons.

**Comment by Malcolmnixon** [comment]
Debugging the issue shows that godot_openxr is correctly generating values in the interval [0.0 .. 1.0]; however godot is rescaling the values to the interval [-1.0 .. 1.0] using the following statement:
```
    float val = p_value.min == 0 ? -1.0f + 2.0f * p_value.value : p_value.value;
````

The sequence of operations leading to the rescaling is as follows:
1. OpenXRApi::update_actions() reads the ACTION_SIDE_TRIGGER getting a value in the interval [0.0 .. 1.0]
2. OpenXRApi::update_actions() calls arvr_api->godot_arvr_set_controller_axis() passing in the value, and additionally a flag **p_can_be_negative** of false indicating the value cannot be negative.
3. godot_arvr_set_controller_axis() builds an InputDefault::JoyAxis value containing the grip value still in the interval [0.0 .. 1.0] and a **min** field of 0 - because the input cannot be negative and so its minimum value is 0.
4. godot_arvr_set_controller_axis() calls input->joy_axis() with this InputDefault::JoyAxis value
5. InputDefault::joy_axis() contains special logic that detects a **min** field of 0 and rescales the interval to [-1.0 .. 1.0] using the line shown above.

I can't find any API documentation indicating the expected behavior of **p_can_be_negative** but from what I'm reading in the code, Godot really wants its joystick inputs to work over the interval [-1.0 .. 1.0], and will actively 'correct' unsigned joysticks to fit this pattern.

Under the assumption that **p_can_be_negative** is really "please correct my unsigned controller", and that we actually want grips and triggers to stay in the interval [0.0 .. 1.0] I did an experiment which changes OpenXRApi::update_actions() to pass in true for **p_can_be_negative** and the result is that InputDefault preserves the interval and you get the full range of grips and triggers in the demo project.

I'm not confident enough to state this is the correct solution because I'm not familiar with Godot's ARVR and Input infrastructure.

**Comment by BastiaanOlij** [comment]
Hmmm, I need to look into this further but this is troublesome. The conversion from `0.0 - 1.0` to `-1.0 - 1.0` is on purpose, or was at some point at least but I can't remember if this is a left over from older XR interfaces or done on purpose.

My gut feeling says that your conclusion is right and p_can_be_negative should always be set to true even if we only have an input ranging from `0.0 - 1.0` as this will take the value as is but I would want to test it with other supported devices just in case there is a difference of behavior here. Especially seeing this logic worked correctly so far on an Index headset, that however could simply be because it maps to an analog input instead of a boolean on.

Let me get back to you once I can repeat your experiments on my index :)

**Comment by Malcolmnixon** [comment]
There was a change on January 14th to how joystick inputs are handled - including for ARVR (https://github.com/godotengine/godot/commit/949ea2b3262efd6fb958fff9500434a865da068f#diff-f79e9f0975cedb6e4c13ad012cdfbb81af189101f457969afb3e00a1b752e09d)

It doesn't resolve the 'issue', but it does move the offending transform around to a new location - godot_arvr_set_controller_axis() function in modules\gdnative\arvr\arvr_interface_gdnative.cpp:413
```
			if (!p_can_be_negative) {
				// Convert to a value between -1.0f and 1.0f.
				value = p_value * 2.0f - 1.0f;
			}
```

I still think clearing p_can_be_negative may be the best choice here, and as the conversion was moved from InputDefault::joy_axis() to godot_arvr_set_controller_axis() the scaling is ARVR specific, and changing it would only affect ARVR joystick inputs.

**Comment by BastiaanOlij** [comment]
Looked into this today and applied a PR with the fix. There must have been a good reason for the 0.0 - 1.0 => -1.0 - 1.0 conversion but this was done a long time ago possibly for a completely different use case. 
After the fix is merged the value will be reported as the XR runtime provides it.
