### ISSUE TITLE
Oculus Quest 2 not reporting valid refresh rates

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot_openxr#158]
Reported by Mikotalik on Discord, running on a Quest 2 `get_available_refresh_rates()` is only reporting 60 and 72 (Quest 1 refresh rates), we're missing the option for 90 and 120.

Possibly something missing in the manifest file, and thus possibly something we need to fix in Godot Core.

**Comment by BastiaanOlij** [comment]
After receiving more feedback it seems the entry `<meta-data android:name="com.oculus.supportedDevices" android:value="quest|quest2"/>` is missing from Godots `android.manifest` file. This will require an upstream change for Godot 3.5 (possibly cherry picked for a 3.4 patch release).

To work around this for the time being you can use the [custom android build system](https://docs.godotengine.org/en/stable/tutorials/export/android_custom_build.html) and follow the following steps:
1) Make sure all export templates are installed in Godot
2) In Godot run `Project->Install Android Build Templates...`
3) In Godot check the `Use Custom Build` checkbox in the export settings
4) Edit the file `Android/build/AndroidManifest.xml` and add the missing line
5) Run your game on the Quest.

This should fix both issues with the refresh rates and with foveated rendering.

See https://developer.oculus.com/documentation/native/android/mobile-native-manifest/ for more info on the manifest file changes.

**Comment by m4gr3d** [comment]
The latest [Godot 3.4.3 RC](https://godotengine.org/article/release-candidate-godot-3-4-3-rc-1) should resolve this issue.
