### ISSUE TITLE
Hand tracking documentation

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_openxr#159]
Update the [Godot OpenXR documentation](https://docs.godotengine.org/en/stable/tutorials/vr/openxr/index.html) with instructions for how to setup and configure hand tracking in a project.

**Comment by BastiaanOlij** [comment]
Done, this can be closed once the upstream documentation is merged I reckon.

**Comment by BastiaanOlij** [comment]
Docs have been merged :)
