### ISSUE TITLE
How is possible to render different objects between eyes when using OpenXR/godot?

### ISSUE THREAD

**Issue by eruffaldi** [GodotVR/godot_openxr#164]
For creating perceptual tricks I would like to have different objects rendered per-eye. 

In three.js layer 1 and 2 map to left and right eye respectively and this could be fine.

Other frameworks provide some form of notification before an eye is rendere allowing to alter the scene.

Thanks

**Comment by m4gr3d** [comment]
@eruffaldi `VIEW_INDEX` shader variable was added in https://github.com/godotengine/godot/pull/48011 (so available in Godot 3.4 and higher) and should allow you to alter rendering per eye.

**Comment by m4gr3d** [comment]
Closing due to the lack of response. Feel free to reopen if you have further inquiries.

**Comment by mgpadalkar** [comment]
Hi @eruffaldi, I guess you may already have the solution as mentioned below:

> @eruffaldi `VIEW_INDEX` shader variable was added in [godotengine/godot#48011](https://github.com/godotengine/godot/pull/48011) (so available in Godot 3.4 and higher) and should allow you to alter rendering per eye.

Just to put it all in one place, here is a sample project using Godot 4.1.2: https://github.com/mgpadalkar/godot_left_right_independent_images
