### ISSUE TITLE
Installing 1.1.1 release shows version as 1.1.0

### ISSUE THREAD

**Issue by rubenquidam** [GodotVR/godot_openxr#165]
Installing the 1.1.1 release from assetlib, it shows on project settings as version 1.1.0. In https://github.com/GodotVR/godot_openxr/releases/download/1.1.1/godot-openxr.zip there is this plugin metadata:

./godot_openxr_1.1.1/addons/godot-openxr/plugin.cfg:version="1.1.0"

I think the package is correct and just the metadata is wrong, based on the timing of the tag/release and when plugin.cfg was last edited for versions, but it got me quite confused for a minute.

**Comment by BastiaanOlij** [comment]
It's just a version number in the config.cfg that was overlooked, it has already been updated to 1.2.0 in preparation for the next release.

**Comment by rubenquidam** [comment]
Thanks for  confirming. I'll leave it to you to close this, perhaps on 1.2.0 release in case somebody else gets confused and find this report.

**Comment by BastiaanOlij** [comment]
@rubenquidam sadly I'm afraid we'll probably make this mistake again in the future because it's so easy to miss :) Yeah I'm leaving this open until we're releasing 1.2.0
