### ISSUE TITLE
Waiting issue in SteamVR

### ISSUE THREAD

**Issue by qdwang** [GodotVR/godot_openxr#167]
Godot version: 3.4.2 x64 windows 10
Device: Quest2
Connection: wifi though Virtual Desktop

I was trying to follow this doc(https://docs.godotengine.org/en/stable/tutorials/vr/openxr/index.html) to run a hello world test on my quest2. 

When I run the project in VD, it can automatically call the SteamVR and it will show a loading splash like normal SteamVR games. 
But it will get stuck at showing the **'waiting...'** with the splash in Quest2. However, on my PC screen, the sky can rotate by tracking my headset.

And no error shows up in the godot editor console. A restart of Steam also won't work.

I don't have any issue to play other games in SteamVR. So don't know what's going on here.

**Comment by BastiaanOlij** [comment]
Hey @qdwang , try and compile the plugin with this PR: #148
The buffer format the current version of the plugin selects when using SteamVR does not seem to be compatible with Oculus Link.

**Comment by qdwang** [comment]
@BastiaanOlij This RP#148 works for me. Will it be included in the next release?

**Comment by BastiaanOlij** [comment]
@qdwang that is definitely the plan, we're just working out some last kinks.

**Comment by qdwang** [comment]
@BastiaanOlij great
