### ISSUE TITLE
Hand meshes misplaced or missing

### ISSUE THREAD

**Issue by tcrass** [GodotVR/godot_openxr#169]
Hi there,

my setup is as follows:

- Godot 3.4.2 on Debian Bullseye
- SteamVR 1.20.4
- ALVR 17.0.1+1643781622+0541c19e
- Oculus (sorry, Meta, of course) Quest 2 with Touch controllers

I built a minimum demo scene consisting of a floor plane, an FPSController and hand meshes right under the left and right controller node, respectively. Additionally, I placed sphere meshes (diameter 10 cm) as siblings to the hand meshes right under the controller nodes.

When running the project through SteamVR/ALVR, the spheres "feel" as though they were exactly where my hands are, but the hand meshes seemed waaay off -- they behaved like they were displaced about 1 m along the y axis and half a meter along the negative z axis. I managed to take a screenshot by stretching my arms as far as possible, demonstrating the described issue:

![image](https://user-images.githubusercontent.com/6480173/154127180-2b911964-bb9b-48d6-a3ce-c6b1f0745162.png)

Only later I realized that the hand meshes were initially switched invisible -- after making them visible, the displacement also became apparent in the Godot editor:

![image](https://user-images.githubusercontent.com/6480173/154127074-e46bab05-58b5-4c6c-8258-431ec7f31579.png)

In order to exclude the possibility that the hand tracking data somehow got messed up on their way through SteamVR and ALVR, I exported the project as Android app and directly installed it on the Quest. Strangely, when running the app, no hand meshes were visible at all, while the spheres still appeared at the correct locations.

So... bug or feature? ;)

Cheers --
Torsten

Edit: Forgot to mention that on the Quest (as opposed to the Godot editor) the hand meshes seem to be rotated around the y axis by about 180 degrees (If I'm not mistaken, I'm looking roughly into direction (0, 1, -1) in the following screenshot):

![image](https://user-images.githubusercontent.com/6480173/154130232-200a9e40-3c9c-4d1c-8d92-4d313a2888e0.png)

**Comment by Malcolmnixon** [comment]
I believe hand tracking (as opposed to controller-tracking) is only supported when running native on the Quest and after putting the controllers down. Running under SteamVR means you're using the Oculus Link which emulates the Rift and has no hand tracking.

Please try re-running on the Quest, putting the controllers down, then waving your hands in front of you to let the quest switch to hand-tracking mode.

**Comment by BastiaanOlij** [comment]
Hi @tcrass ,

> I built a minimum demo scene consisting of a floor plane, an FPSController and hand meshes right under the left and right controller node, respectively.

This is your problem I'm afraid, the hand mesh scenes should be placed under the ARVROrigin (FPController) node, not under the left and right hand controllers. Hand tracking is completely separate from controller tracking in OpenXR. It tracks the location and orientation of your palm. Also hand tracking can work without any controllers. 

See https://docs.godotengine.org/en/stable/tutorials/vr/openxr/handtracking.html for more information.

**Comment by BastiaanOlij** [comment]
Also the sad fact is that the spec isn't very clear about the use cases and each vendor has taken a different take. So SteamVR does inferring hand tracking along side real hand tracking where the sensor on controllers are used to make a guestimate of the hands and finger positions, while Oculus so far only seems to support hand tracking for real hand tracking and requires developers to come up with their own solution for animating a hand model based on controller inputs.

**Comment by tcrass** [comment]
Ah, stupid me! Should have read the documentation more carefully... I didn't distinguish between hand tracking and controller tracking! And I thought the hand meshes provided by the plugin would serve no other purpose than visualizing controller position -- like in the VR starter tutorial at https://docs.godotengine.org/en/stable/tutorials/vr/openvr/vr_starter_tutorial/index.html

I'm perfectly fine with pure controller tracking for now -- pity, though, that at least with SteamVR the controller's get_mesh() method doesn't return anything.

Anyway, my greatest concern right now is how to improve the terrible frame rate I got with ALVR on Linux...

Cheers --
Torsten

**Comment by Malcolmnixon** [comment]
Lol, the reason I guessed this was the issue was because I reported exactly the same bug with exactly the same results about a month ago - https://github.com/GodotVR/godot_openxr/issues/155. I thought I'd get the pretty valve hand models being driven by the controllers.

We may want to consider something to prevent similar confusion popping up periodically. Perhaps improved documentation would help, but its so simple to confuse the "hand tracking" vs "controller tracking" of hands.

**Comment by tcrass** [comment]
> Lol, the reason I guessed this was the issue was because I reported exactly the same bug with exactly the same results about a month ago - #155. I thought I'd get the pretty valve hand models being driven by the controllers.

Yeah, it all seems still pretty experimental and fragile... Yet I'm full of awe what open source projects like Godot and ALVR are capable of! Couple of years ago, I never would have guessed that I myself would one day venture developing a VR application just for fun in my (unfortunately: rather sparse) leasure time... A big thank you to all those VR gurus out there!
 
> We may want to consider something to prevent similar confusion popping up periodically. Perhaps improved documentation would help, but its so simple to confuse the "hand tracking" vs "controller tracking" of hands.

...in particular since, for instance, the Quest _always_ shows some ghostly, partially animated hands, even if what they call "hand tracking" is disabled. :-/

Cheers --
Torsten

**Comment by BastiaanOlij** [comment]
@tcrass yeah Oculus will switch between the full hand tracking approach, and just hand meshes they animate based on inputs. Its really a shame they aren't doing the same as Valve in just mimicking hand tracking through the hand tracking API based on controller input.

**Comment by tcrass** [comment]
So since the behavior described in my initial report was caused just by me not using the hand nodes correctly, I guess this issue can be closed?

Cheers --
Torsten
