### ISSUE TITLE
predictedDisplayPeriod jumping to ludicrously high fixed value.

### ISSUE THREAD

**Issue by CherrySodaPop** [GodotVR/godot_openxr#173]
```
frameState.predictedDisplayPeriod: 41666664
frameState.predictedDisplayPeriod: 41666664
frameState.predictedDisplayPeriod: 41666664
frameState.predictedDisplayPeriod: 59652319710029072
ERROR: OpenXR failed to locate space! [XR_ERROR_TIME_INVALID] at: OpenXRApi::xr_result (src\openxr/OpenXRApi.h:343)
frameState.predictedDisplayPeriod: 59652319710029072
ERROR: OpenXR failed to locate space! [XR_ERROR_TIME_INVALID] at: OpenXRApi::xr_result (src\openxr/OpenXRApi.h:343)
frameState.predictedDisplayPeriod: 59652319710029072
frameState.predictedDisplayPeriod: 59652319710029072
ERROR: OpenXR Failed to locate view space in play space! [XR_ERROR_TIME_INVALID] at: OpenXRApi::xr_result (src\openxr/OpenXRApi.h:343)
frameState.predictedDisplayPeriod: 55555552
frameState.predictedDisplayPeriod: 55555552
frameState.predictedDisplayPeriod: 55555552
frameState.predictedDisplayPeriod: 55555552
frameState.predictedDisplayPeriod: 55555552
frameState.predictedDisplayPeriod: 55555552
```
Issue began at this [commit.](https://github.com/GodotVR/godot_openxr/commit/c9b42661d4596e1906edff1fc3528dd9611c22da)

**Comment by BastiaanOlij** [comment]
Hi @CherrySodaPop ,

Can you provide some more information on what system this is on? We're getting the timing information we're using from the XR runtime so knowing which runtime is providing incorrect information will help in finding out what to do about it.

Thanks!

**Comment by CherrySodaPop** [comment]
Heya! I'm using Godot 3.4.2 on Windows 10, the issue only seems to happen on the SteamVR runtime.

**Comment by BastiaanOlij** [comment]
Hi @CherrySodaPop ,

Thanks for that, I'll start investigating and see what I can find, could you also let us know which headset you are using?

**Comment by CherrySodaPop** [comment]
Using the Quest 2 headset with link cable.

**Comment by BastiaanOlij** [comment]
@CherrySodaPop it's a bit of a workaround but can you try #176 ?

**Comment by CherrySodaPop** [comment]
This seems to have done the trick!
No errors and tracking doesn't get lost anymore.
