### ISSUE TITLE
Missing shared library when upgrading to AGP 7.1+

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_openxr#187]
Upgrading to AGP 7.1+ causes the `openxr_loader` shared library to go missing from the generated Android library AAR binary.

##### Expected behavior:
- Checkout the project using the [build instructions](https://github.com/GodotVR/godot_openxr#building-this-module) and run the command to generate the shared libraries:
  - `./gradlew generateSharedLibs`
- This should generate two shared libraries in the `android/build/outputs/sharedLibs/release/arm64-v8a` directory: `libopenxr_loader.so` and `libgodot_openxr.so`.

##### Buggy behavior:
- Delete the `android/build` directory: `rm -rf android/build`
- Navigate to `config.gradle` and update the `gradlePluginVersion` to `7.1.2`
- Navigate to `gradle/wrapper/gradle-wrapper.properties` and change the version of gradle to `7.2`: `distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip`
- Run the command to generate the shared libraries again: `./gradlew generateSharedLibs`
- Notice only 1 shared library is generated this time in the `android/build/outputs/sharedLibs/release/arm64-v8a` directory: `libgodot_openxr.so`

**Comment by akien-mga** [comment]
I can confirm that this issue is still reproducible with AGP 7.2.1 and Gradle 7.4.2:
```diff
diff --git a/config.gradle b/config.gradle
index 17ecf55..d890471 100644
--- a/config.gradle
+++ b/config.gradle
@@ -1,6 +1,6 @@
 ext {
     versions = [
-            gradlePluginVersion: '7.0.3',
+            gradlePluginVersion: '7.2.1',
             compileSdk         : 30,
             minSdk             : 19, // Also update 'android/src/main/AndroidManifest.xml#minSdkVersion' value
             targetSdk          : 30, // Also update 'android/src/main/AndroidManifest.xml#targetSdkVersion' value
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index a0f7639..92f06b5 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -1,5 +1,5 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-all.zip
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
```
