### ISSUE TITLE
HTC VIVE Focus 3 Controller Mappings Incorrect

### ISSUE THREAD

**Issue by Psychophylaxis2** [GodotVR/godot_openxr#190]
Running the OpenXR demo via SteamVR, the controllers do not map correctly on a HTC VIVE Focus 3.
Trigger displays in the info box as Select
A/X displays in the info box as Menu

No other controls function including the analog sticks

Quick debug shows that get_joystick_axis always returns null

Poses for moving the sticks do display correctly though.

**Comment by BastiaanOlij** [comment]
Which version are you testing? The official release or a master build? We only recently added the bindings for some of the newer HTC controller models so it is likely just binding it on the generic controller which indeed has very limited inputs. It should show in the output log what its binding the controllers too. 

Try the latest pre-release build to see if it makes a difference, if it doesn't possibly we need to enabled some extensions:
https://github.com/GodotVR/godot_openxr/releases

That said, Focus 3 is a stand along headset so I'm assuming HTC has something like Oculus' Link? I wonder how it presents itself to SteamVR.

**Comment by Psychophylaxis2** [comment]
I was running 1.1.0. The latest build does indeed work correctly and I'll close this ticket. 

Thanks a lot and for all your amazing work here. Godot knocks the pants off Unity for GLTF import that actually works and rapid development, we just need to get that DirectX backend kickstarted so it works with Hololens (I am trying to persuade my company to help out on this front).

For reference the Focus 3 is standalone with Wifi 6 connection. In standalone mode, it doesn't yet fully support OpenXR on Android, hence why I'm streaming from a PC via Steam.
Much like Oculus it uses the VIVE Business Streaming application to map to SteamVR. Its more clunky than Oculus link but getting better all the time. Of course for business use it means I don't need a Facebook account, which is a deal breaker for my company.
The controllers are not the same as the old VIVE wands, closer to Oculus design.
