### ISSUE TITLE
Native OpenXR in 4.0?

### ISSUE THREAD

**Issue by hoontee** [GodotVR/godot_openxr#22]
Seems like a no-brainer to have this sort of thing built in to the engine.

**Comment by BastiaanOlij** [comment]
We agree, getting hired to work on that full time from next month onwards: 

https://godotengine.org/article/godot-engine-receiving-support-funded-facebook-reality-labs

**Comment by hoontee** [comment]
Ah, that's good news! The wording in the article made me believe that it would still exist as a GDNative plugin.

**Comment by l33tlinuxh4x0r** [comment]
The current OpenXR addon is crashing godot 4.0 for me.

**Comment by paul-marechal** [comment]
> We agree, getting hired to work on that full time from next month onwards:

@BastiaanOlij does that mean that this addon will become obsolete going forward with Godot 4.0? If so, is there a rough ETA? Wondering how worthwhile it will be to work with and use this repository :)

**Comment by BastiaanOlij** [comment]
> 
> 
> The current OpenXR addon is crashing godot 4.0 for me.

Yes the current add on only works with Godot 3.x

**Comment by BastiaanOlij** [comment]
> 
> 
> > We agree, getting hired to work on that full time from next month onwards:
> 
> @BastiaanOlij does that mean that this addon will become obsolete going forward with Godot 4.0? If so, is there a rough ETA? Wondering how worthwhile it will be to work with and use this repository :)

That is still up in the air, it is possible we will integrate it, it is possible we will keep it as a plugin. From a coding point of view things will work similar regardless of the approach taken. 

As for ETA, there were a few things that came in between but I'm at the tail end of adding stereoscopic support back into Godot 4 and will start working on making some of the plugins work next.

**Comment by hoontee** [comment]
Added in https://github.com/godotengine/godot/pull/56394.
