### ISSUE TITLE
OpenXRApi crash

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot_openxr#229]
I get error 
![obraz](https://user-images.githubusercontent.com/51274570/183908553-5d53641c-e7d9-4a06-8d44-f02267aa2b61.png)
with `first_person_controller_vr.gd` script line `33` on initialization

aditionaly it detects those interfaces on pc windows 10
![obraz](https://user-images.githubusercontent.com/51274570/183908832-811fc795-100e-4246-bb8c-e761ceb156a4.png)

Just to clarify it was working before but it stopped

Also those are my all plugins
![obraz](https://user-images.githubusercontent.com/51274570/183909098-1f0967ad-72c9-4a6b-8d4a-940147c59e3e.png)

**Comment by pietru2004** [comment]
Erm I found it only happens with WMR.

**Comment by BastiaanOlij** [comment]
Hi @pietru2004,

Indeed, WMR only support DirectX, it doesn't support Vulkan nor OpenGL. You can still run games by using SteamVR.

**Comment by pietru2004** [comment]
Well I guess this can be closed
