### ISSUE TITLE
ARVRCamera transform not updated in Godot

### ISSUE THREAD

**Issue by NicoZobernig** [GodotVR/godot_openxr#4]
Hi, after some talk in the Godot discord, it seems there is a bug with the ARVRCamera Node not being updated properly. It always stays at the origin. (1,0,0 - 0,1,0 - 0,0,1 - 0,0,0)

@BastiaanOlij mentioned that it is only returning the left and right eye positions for rendering, not the center position that is used to track the camera node in Godot. According to him, this is the code that needs to be fixed up: https://github.com/GodotVR/godot_openxr/blob/master/src/ARVRInterface.cpp#L155 

This then results in some buggy behavior, where child nodes don't follow the camera for example (as the parent node transform doesn't seem to change, when it is in fact moving in game). Also, since the transform doesn't update, `ARVRServer.get_hmd_trasnform()` as well as `get_camera_transform()` from the camera node always return the origin (identity rotation and zero translation)

**Comment by ChristophHaag** [comment]
I implemented this using `XR_REFERENCE_SPACE_TYPE_VIEW` in 883fa0992e615f46d86940304d485643b94e5389.

Now attaching a node to the ARVRCamera and translating the node a little in -z direction keeps the attached node "head locked" in the view of the HMD.

Let me know if there are any issues with it.

**Comment by BastiaanOlij** [comment]
Looks good @ChristophHaag , better to create PRs through, while a bit overkill when just the two of us working on stuff it does allow for recording feedback before we merge :)

**Comment by ChristophHaag** [comment]
Sure, in the future I will do PRs for significant code changes. Might have already been good in this case for feedback on function naming.

**Comment by BastiaanOlij** [comment]
I guess this can be closed?
